create table tbl_Employees(
emp_Id int primary key identity,
emp_First_Name nvarchar(15),
emp_Middle_Name nvarchar(15),
emp_Last_Name nvarchar(15),
emp_Date_Of_Birth datetime,
emp_NID_Number nvarchar(30),
emp_Father_Name nvarchar(50),
emp_Mother_Name nvarchar(50),
emp_Religion nvarchar(20),
emp_Gender nvarchar(8),
emp_Marital_Status nvarchar(10),
emp_Spouse_Name nvarchar(50),
emp_Present_Address nvarchar(100),
emp_Permanent_Address nvarchar(100),
emp_Phone nvarchar(18),
emp_Email nvarchar(max),
emp_Blood_Group nvarchar(5),
emp_Last_Academic_Certification nvarchar(50),
emp_Last_Academic_Certification_Result nvarchar(15),
emp_Joining_Date datetime,
emp_Designation nvarchar(25),
emp_Salary decimal(8,2),
emp_Image nvarchar(max),
emp_Status nvarchar(10),
Created_Date datetime,
Created_By nvarchar(15) Default 'Admin'
)